/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const purchases_Logic = require('./code/purchases-logic');
const redemptions_Logic = require('./code/redemptions-logic');
const customers_Logic = require('./code/customers-logic');

class my_new_projectSrv extends LCAPApplicationService {
    async init() {

        this.on('CREATE', 'Purchases', async (request, next) => {
            await purchases_Logic(request);
            return next();
        });

        this.on('CREATE', 'Redemptions', async (request, next) => {
            await redemptions_Logic(request);
            return next();
        });

        this.before('READ', 'Customers', async (request) => {
            await customers_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    my_new_projectSrv
};